### ISSUE TITLE
Error on MissingRequiredTemplateFiles failures

### ISSUE THREAD

**Issue by sdn90** [Shopify/theme-check-action#14]
``` 
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at /index.js:72:20
    at Array.map (<anonymous>)
    at /index.js:70:10
    at async /index.js:67:20
```

When the MissingRequiredTemplateFiles rules fail, the path is null and causes this to throw.

**Comment by alfredojrm** [comment]
Hi, @charlespwd I have the same error in my theme check github action, have you any information for this error? 

Left here is a capture of my error 
![image](https://user-images.githubusercontent.com/87659707/180577793-df49d11e-1618-4324-9961-0bcced57953f.png)
