### ISSUE TITLE
Theme Check not checking ParserBlockingJavaScript

### ISSUE THREAD

**Issue by binarymonkey84** [Shopify/theme-check-action#47]
I ran a test action on a pull request, where I'd added a parser blocking script tag.

Theme Check did not add any line annotations next to the code, even though the docs say this check is on by default and severity is `error`.

Theme Check reference for this specific issue:
https://shopify.dev/docs/storefronts/themes/tools/theme-check/checks/parser-blocking-javascript

Screenshot of commit in PR with annotations elsewhere from Theme Check, but not on the `script` tag where it's expected:

![image](https://github.com/user-attachments/assets/b2a1d91b-7698-462f-b926-0ea569dee78b)

Is this action somehow out of date with the latest checks, or is there some bug or configuration issue?

I did notice on the "Theme Check Report" under "ThemeCheck Configuration" that `ParserBlockingJavaScript` is **not** listed, but `ParserBlockingScript` is. Not sure if that's the issue or not?

![image](https://github.com/user-attachments/assets/6c1dd83e-8873-4a23-bb7a-db1c07e33084)

**Comment by charlespwd** [comment]
> Parser blocking inline script tags are still a performance issue. 

:wave: I find myself a bit less worried about those than I am about downloading random libs from CDNs which incur quite a lot more costs: download(https handshake, server latency, download), decompress, parse, execute. An inline script tag is already available, is generally smaller and only has the parse + execute cost. 

It's still parse + execute... but, I don't know, doesn't feel like quite the footgun in terms of scale vs the download + decompress in the <head>. Inline script tags are also usually down the documents, images and CSS has probably already loaded... 

Do you have a particular common use case in mind that you think is particularly bad?
